PROJECT_ID = "classdemo-425210"
BUCKET_NAME = "gs://vertex-mlops-bucket990"
BQ_DATASET = "bigquery-public-data.california_housing_built"
BQ_TABLE = "ml_datasets"
MODEL_NAME = "california_housing_model"
REGION = "us-central1"