PROJECT_ID = "classdemo-425210"
BUCKET_NAME = "gs://vertex-mlops-bucket990"
BQ_DATASET = "bigquery-public-data.new_york_taxi_trips"
BQ_TABLE = "tlc_yellow_trips_2022"
MODEL_NAME = "nyc_taxi_model"
REGION = "us-central1"
